### ISSUE TITLE
(bug) (types) Option to Skip mas upgrade

### ISSUE THREAD

**Issue by lucymhdavies** [skylarmacdonald/bork#18]
There's a bunch of mas issues at the moment where `mas` thinks apps are outdated, when they're not:

```
Sakura:~ strawb$ mas outdated
1482454543 Twitter (8.60 -> 8.59.1)
1480068668 Messenger (97.11.116 -> 96.0)
411643860 DaisyDisk (4.12.1 -> 4.12)
```

Currently, bork will attempt a `mas upgrade` every time it checks one of these "outdated" apps

https://github.com/mas-cli/mas/issues/290 is the bug on the mas side

**Comment by skylarmacdonald** [comment]
Going to mark this as a bug, since it's undesirable behaviour. Need to understand if the limitations in the `mas` CLI that meant we couldn't upgrade a specific app before (see [caveat](https://skylarmacdonald.github.io/bork/types#type-mas)) is still the case.

If `mas` is incorrectly reporting outdated applications, we can't fix that on Bork's end.

**Comment by lucymhdavies** [comment]
Bug fixed on the `mas` side

**Comment by skylarmacdonald** [comment]
Cool. Right now the `mas` output is stubbed in a fixture so I'll need to do some soft testing on my local machine to double check Bork is behaving as expected; once I have done this I think the move is to disable the `mas` forced upgrade (if we can) and then only upgrade when it finds a status of `outdated` and is satisfying.

**Comment by skylarmacdonald** [comment]
I think this is fixed without requiring any action on Bork's side, so I'm going to change the documentation and then call this closed.
